/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeSecurity */

#ifndef _Included_NativeSecurity
#define _Included_NativeSecurity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeSecurity
 * Method:    check
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_NativeSecurity_check
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
